# Agent Engine Service
# Note: This service requires the shared infrastructure to be running
# Start infrastructure first: cd ../infrastructure && docker-compose up -d

version: '3.8'

services:
  agent-engine:
    build: .
    container_name: tahoe-agent-engine
    ports:
      - "8001:8001"
    environment:
      # For local development (host machine)
      DATABASE_URL: postgresql://tahoe:tahoe@host.docker.internal:5435/tahoe
      REDIS_URL: redis://host.docker.internal:6382
      # For production or docker network mode
      # DATABASE_URL: postgresql://tahoe:tahoe@tahoe-postgres:5432/tahoe
      # REDIS_URL: redis://tahoe-redis:6379
      PORT: 8001
      ENVIRONMENT: development
      DEBUG: "true"
      SERVICE_NAME: agent-engine
      SERVICE_TOKEN: ${SERVICE_TOKEN:-dev-token}
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - tahoe-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  tahoe-network:
    external: true
    name: tahoe_network