# Agent Engine Service
# Note: This service requires the shared infrastructure to be running
# Start infrastructure first: cd ../infrastructure && docker-compose up -d

version: '3.8'

services:
  agent-engine:
    build: .
    container_name: tahoe-agent-engine
    ports:
      - "8001:8001"
    environment:
      # Environment
      ENVIRONMENT: ${ENVIRONMENT:-development}
      
      # Service Configuration
      HOST: 0.0.0.0
      PORT: 8001
      DOMAIN: ${DOMAIN:-tahoe.local}
      
      # Database Configuration (using host machine services)
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5435
      DATABASE_NAME: tahoe
      DATABASE_USER: tahoe
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-tahoe}
      DATABASE_SCHEMA: agent_engine
      
      # Redis Configuration (using host machine services)
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6382
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_PREFIX: agent-engine:
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      
      # Service Authentication
      SERVICE_TO_SERVICE_TOKEN: ${SERVICE_TO_SERVICE_TOKEN:-}
      
      # Optional service URLs (computed if not set)
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL:-}
      BILLING_SERVICE_URL: ${BILLING_SERVICE_URL:-}
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - tahoe-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  tahoe-network:
    external: true
    name: tahoe_network