version: '3.8'

# Shared infrastructure services only
services:
  postgres:
    image: postgres:16-alpine
    container_name: tahoe-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tahoe
      POSTGRES_USER: tahoe_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tahoe-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tahoe_user -d tahoe"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tahoe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - tahoe-network
    command: redis-server --appendonly yes

networks:
  tahoe-network:
    name: tahoe-network
    driver: bridge

volumes:
  postgres-data:
  redis-data: