version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tahoe-postgres
    environment:
      POSTGRES_USER: tahoe
      POSTGRES_PASSWORD: tahoe
      POSTGRES_DB: tahoe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tahoe -d tahoe"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tahoe-network

  redis:
    image: redis:7-alpine
    container_name: tahoe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes
    networks:
      - tahoe-network

volumes:
  postgres_data:
  redis_data:

networks:
  tahoe-network:
    driver: bridge