services:
  # Main Transcription Service
  app:
    build: .
    container_name: transcription_app
    ports:
      - "9100:9100"  # Main API
      - "9101:9101"  # Admin/monitoring
    environment:
      - DATABASE_URL=postgresql://tahoe_user:tahoe_pass@tahoe-postgres:5432/tahoe
      - REDIS_URL=redis://tahoe-redis:6379
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERVICE_AUTH_TOKEN=${SERVICE_AUTH_TOKEN}
      - POLL_INTERVAL=${POLL_INTERVAL:-60}
      - WORKER_COUNT=${WORKER_COUNT:-4}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - JOB_TIMEOUT=${JOB_TIMEOUT:-1800}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-transcribe}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-pro}
      - GEMINI_MAX_TOKENS=${GEMINI_MAX_TOKENS:-8192}
      - GEMINI_TEMPERATURE=${GEMINI_TEMPERATURE:-0.1}
      - S3_AUDIO_BUCKET=${S3_AUDIO_BUCKET}
      - S3_TRANSCRIPT_BUCKET=${S3_TRANSCRIPT_BUCKET}
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    networks:
      - tahoe-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9100/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  tahoe-network:
    external: true