apiVersion: "agent-engine/v1"
kind: "AgentSpec"
metadata:
  name: "stateful-workflow"
  version: "1.0.0"
  description: "Custom agent that maintains state across executions and supports workflow restart"
  tags: ["custom", "workflow", "stateful", "restart"]
  author: "tahoe-platform"
  created_at: "2025-08-14T00:00:00Z"

spec:
  agent:
    type: "custom"
    custom_class: "StatefulWorkflow"
    parameters:
      workflow_steps: ["analyzer", "simple_demo", "chat_assistant"]
      allow_restart: true
      description: "Stateful workflow that can resume from failure points"
  
  sub_agents:
    - spec_ref: "examples/analyzer"
      condition: "true"
    - spec_ref: "examples/simple_demo"
      condition: "true"
    - spec_ref: "examples/chat_assistant"
      condition: "true"
  
  validation:
    input_schema:
      type: "object"
      properties:
        data:
          type: "object"
          description: "Input data for workflow processing"
        restart_from_step:
          type: "integer"
          description: "Step number to restart from (0-based)"
          minimum: 0
          default: 0
        force_restart:
          type: "boolean"
          description: "Force restart even if no previous failure"
          default: false
      required: ["data"]
    
    output_schema:
      type: "object"
      properties:
        completed_steps:
          type: "array"
          items:
            type: "string"
          description: "List of successfully completed workflow steps"
        failed_steps:
          type: "array"
          items:
            type: "string"
          description: "List of failed workflow steps"
        total_steps:
          type: "integer"
          description: "Total number of steps in the workflow"
        restart_count:
          type: "integer"
          description: "Number of times workflow has been restarted"
        success:
          type: "boolean"
          description: "Whether the workflow completed successfully"
        current_step:
          type: "integer"
          description: "Current step number (0-based)"

examples:
  - name: "Successful Workflow Execution"
    input:
      data:
        content: "Process this through the complete workflow"
        format: "text"
    expected_output:
      completed_steps: ["analyzer", "simple_demo", "chat_assistant"]
      failed_steps: []
      total_steps: 3
      restart_count: 0
      success: true
      current_step: 3
  
  - name: "Workflow with Restart"
    input:
      data:
        content: "Process with potential restart needed"
        simulate_failure: true
      force_restart: true
    expected_output:
      completed_steps: ["analyzer"]
      failed_steps: ["simple_demo"]
      total_steps: 3
      restart_count: 1
      success: false
      current_step: 1